project_bk/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.index, name='index'), # /daiary
    path('add/', views.add, name='add'), # /diary/add
    path('update/<int:pk>/', views.update, name='update'), # /diary/update/1 <int:pk> はint（整数）のpk（primary_key）に紐付ける
    path('delete/<int:pk>/', views.delete, name='delete'), # /diary/delete/1
    path('detail/<int:pk>/', views.detail, name='detail'), # /diary/detail/1
]

project_bk/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
]

project_bk/diary/models.py
from django.db import models
from django.utils import timezone # pythonだとdatetime.nowで現在日時&時刻を取得できるが、djangoはtimezone.nowという独自の機能がある

class Day(models.Model):
  # id = models.AutoField(primary_key=True) # 更新の際にprimary_keyを内部的に生成している。AutoFieldは1,2,3,4と順に作成する(この記述がなくてもdjangoが自動的に生成してくれる)
  title = models.CharField('タイトル', max_length=200)
  text = models.TextField('本文')
  date = models.DateTimeField('日付', default=timezone.now)

project_bk/diary/forms.py
from django import forms # フォームをinport
from .models import Day

# 日付をformで作成する
class DayCreateForm(forms.ModelForm): # 引数にforms.Formというのもある
  class Meta:
    model = Day #対象となるmodel
    fields = '__all__' # modelのfields（フィールド）。特定のものを指定する場合 ('title', 'text', 'date')のようにタプル型にする

project_bk/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DayCreateForm
from .models import Day


# 関数型のview
def index(request):
  context = {
    'day_list': Day.objects.all(), #データベースに保存されているデータを全て取得する
  }
  return render(request, 'diary/day_list.html', context)


def add(request):
  # 送信内容を基にフォームを作る。POSTじゃなければ空のフォーム
  form = DayCreateForm(request.POST or None)

  # method=POST の時の処理かつformの入力内容が問題なければ
  if request.method == 'POST' and form.is_valid():
    form.save() # modelがデータベースに保存される
    return redirect('diary:index') #リダイレクト先を指定

  # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示
  context = {
    'form': form
  }
  return render(request, 'diary/day_form.html', context)


def update(request, pk):
  # urlのpkを基にDayを取得
  day = get_object_or_404(Day, pk=pk)

  form = DayCreateForm(request.POST or None, instance=day) #instance=day は取得したdayモデルに紐付ける

  # method=POST の時の処理かつformの入力内容が問題なければ
  if request.method == 'POST' and form.is_valid():
    form.save() # modelがデータベースに保存される
    return redirect('diary:index') #リダイレクト先を指定

  # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示
  context = {
    'form': form
  }
  return render(request, 'diary/day_form.html', context)


def delete(request, pk):
  # urlのpkを基にDayを取得
  day = get_object_or_404(Day, pk=pk)

  # method=POST の時の処理かつformの入力内容が問題なければ
  if request.method == 'POST':
    day.delete() # dayインスタンスを削除する
    return redirect('diary:index') #リダイレクト先を指定

  # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示
  context = {
    'day': day #dayモデルインスタンスを渡す
  }
  return render(request, 'diary/day_confirm_delete.html', context)


def detail(request, pk):
  # urlのpkを基にDayを取得
  day = get_object_or_404(Day, pk=pk)

  # 通常時のページアクセスや、入力内容に誤りがあればまたページを表示
  context = {
    'day': day #dayモデルインスタンスを渡す
  }
  return render(request, 'diary/day_detail.html', context)

project_bk/diary/templates/diary/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>日記アプリケーション</title>
</head>
<body>
  <div class="container"></div>
    <nav class="nav">
      <a class="nav-link" href="{% url 'diary:index' %}">一覧</a>
      <a class="nav-link" href="{% url 'diary:add' %}">追加</a>
    </nav>
    {% block content %}
    {% endblock %}
  </div>
  
</body>
</html>

project_bk/diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}
{% block content %}

<form action="" method="POST">
  <table>
    <tr>
      <th>{{ day.title.label }}</th>
      <td>{{ day.title }}</td>
    </tr>
    <tr>
      <th>{{ day.text.label }}</th>
      <td>{{ day.text }}</td>
    </tr>
    <tr>
      <th>{{ day.date.label }}</th>
      <td>{{ day.date }}</td>
    </tr>
  </table>
  <p>こちらのデータを削除しますか？</p>
  <button type="submit">送信</button>
  {% csrf_token %} <!-- cross-site request forgeries 対策。POSTの場合は必要 -->
</form>

{% endblock %}

project_bk/diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}
{% block content %}

<table>
  <tr>
    <th>{{ day.title.label }}</th>
    <td>{{ day.title }}</td>
  </tr>
  <tr>
    <th>{{ day.text.label }}</th>
    <td>{{ day.text | linebreaksbr }}</td> <!-- linebreaksbrは改行コードをbrに置換してくれる（django機能）urlizeという自動でaタグを生成してくれるものもある -->
  </tr>
  <tr>
    <th>{{ day.date.label }}</th>
    <td>{{ day.date }}</td>
  </tr>
</table>

{% endblock %}

project_bk/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}
{% block content %}

<form action="" method="POST">
  <table>
    <tr>
      <th>{{ form.title.label }}</th>
      <td>{{ form.title }}</td>
    </tr>
    <tr>
      <th>{{ form.text.label }}</th>
      <td>{{ form.text }}</td>
    </tr>
    <tr>
      <th>{{ form.date.label }}</th>
      <td>{{ form.date }}</td>
    </tr>
  </table>
    <!-- {{ form.as_p }} modelで設定したform内容を反映（as_p は入力欄がpタグに含まれて送信される） -->
  <button type="submit">送信</button>
  {% csrf_token %} <!-- cross-site request forgeries 対策。POSTの場合は必要 -->
</form>

{% endblock %}

project_bk/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}
{% block content %}
<h1>日記一覧</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>日付</th>
      <th>更新</th>
      <th>削除</th>
    </tr>
  </thead>
{% for day in day_list %}
  <tbody>
    <tr>
      <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
      <td>{{ day.date }}</td>
      <td><a href="{% url 'diary:update' day.pk %}">更新</a></td> <!-- pkはprimary_keyの意味 -->
      <td><a href="{% url 'diary:delete' day.pk %}">削除</a></td> <!-- delete -->
    </tr>
  </tbody>
{% endfor %}
</table>

{% endblock %}