project2/employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'

urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
]

project2/project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('employee.urls')),
]

project2/employee/models.py
from django.db import models
from django.utils import timezone

# 部署
class Department(models.Model):
  name = models.CharField('部署名', max_length=20)
  created_at = models.DateTimeField('日付', default=timezone.now)

  def __str__(self): # 特殊メソッド__str__を使うことで選択項目をわかりやすくする（self.name）
    return self.name

# 部活
class Club(models.Model):
  name = models.CharField('部活名', max_length=20)
  created_at = models.DateTimeField('日付', default=timezone.now)

  def __str__(self): # 特殊メソッド__str__を使うことで選択項目をわかりやすくする（self.name）
    return self.name


class Employee(models.Model):
  first_name = models.CharField('名', max_length=20)
  last_name = models.CharField('姓', max_length=20)
  email = models.EmailField('メールアドレス', blank=True) # EmailFieldはメール形式じゃないとエラーを出す。blank=Trueで空文字列だけどもOKにする
  department = models.ForeignKey(
    Department, verbose_name='部署', on_delete=models.PROTECT, # models.PROTECTで部署と紐付いた従業員がいる場合部署を削除できなくする。CASCADEで関連していても削除できる
  )
  club = models.ManyToManyField(
    Club, verbose_name='部活', # 第一引数にClubと紐付ける。verbose_nameは説明名
  )
  created_at = models.DateTimeField('日付', default=timezone.now) # 社員を作成した日付
  # address = models.CharField('住所', max_length=20, default="aaa") # defaultはblank=Trueで空白OKにもできる
  models.OneToOneField

  # コメント

  def __str__(self):
    return '{0} {1} {2}'.format(self.last_name, self.first_name, self.department)

project2/employee/forms.py
from django import forms
from .models import Club, Department

class SearchForm(forms.Form):
  club = forms.ModelChoiceField(
    queryset=Club.objects, label='サークル', required=False #requiredはTrueだと必須
  )

  department = forms.ModelChoiceField(
    queryset=Department.objects, label='部署', required=False
  )

project2/employee/views.py
from django.views import generic
from .forms import SearchForm
from .models import Employee

class IndexView(generic.ListView):
  # template_name = 'employee/employee_list.html'
  model = Employee
  paginate_by = 1

  def get_context_data(self):
    context = super().get_context_data()
    context['form'] = SearchForm(self.request.GET) #基の辞書にformを追加
    return context

  def get_queryset(self):
    form = SearchForm(self.request.GET)
    form.is_valid() #これをしないと、cleaned_dataができない

    #まずは全社員を取得
    queryset = super().get_queryset()

    #部署の選択があれば部署で絞込み
    department = form.cleaned_data['department']
    if department:
      queryset = queryset.filter(department=department)

    
    #サークルの選択があればサークルで絞込み
    club = form.cleaned_data['club']
    if club:
      queryset = queryset.filter(club=club)
    return queryset

project2/employee/templates/employee/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>

  <nav>
    <a href="#">ロゴ</a>
    <button type="button">
      ボタン
    </button>
    <ul>
      <li>
        <a href="{% url 'employee:index' %}">一覧</a>
      </li>
      {% if user.is_super %}
      <li>
        <a href="{% url 'admin:employee_employee_add' %}">追加</a>
      </li>
      {% endif %}
    </ul>
    <form action="">
      <input type="text" placeholder="Search">
      <button type="submit">Search</button>
    </form>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

project2/employee/templates/employee/employee_list.html
{% extends 'employee/base.html' %}
{% block content %}

<form action="" method="GET">
  {{ form }}
  <button type="submit">検索</button>
</form>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>姓</th>
      <th>名</th>
      <th>メール</th>
      <th>部署</th>
      <th>部活</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employee_list %}
    <tr>
      <td>{{ employee.pk }}</td>
      <td>{{ employee.last_name }}</td>
      <td>{{ employee.first_name }}</td>
      <td>{{ employee.email }}</td>
      <td>{{ employee.department }}</td>
      <td>{% for club in employee.club.all %}{{ club }} {% endfor %}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include 'employee/page4.html' %}
{% endblock %}

project2/employee/templates/employee/page4.html
<nav aria-label="Page Navigation">
  <ul class="pagnation">
    {% if page_obj.has_previous %}
    <li>
      <a href="?page={{ page_obj.previous_page_number }}">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}

    {% for link_page in page_obj.paginator.page_range %}
      {% if link_page == page_obj.number%}
        <li class="active">
          <a href="?page={{link_page}}">
            {{ link_page }}
          </a>
        </li>
      {% else %}
        <li>
          <a href="?page={{link_page}}">
            {{ link_page }}
          </a>
        </li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}

  </ul>
</nav>